- op: replace
  path: /spec/template/spec/providerSpec/value/platform
  value:
    config: |-
      location: "centralus"
      resourcegroup: "{{RESOURCE_GROUP}}"
      instances:
        type:  "Standard_D2_v3"
        image: "{{IMAGE_RESOURCE_ID}}"
        network: "{{NETWORK}}"
        subnet: "{{SUBNET}}"
        disks:
          size: 10
    type: azure