---
kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/talos-systems/cluster-api-provider-talos

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
  - name: tmp
    path: /tmp

steps:
  - name: fetch
    image: docker:git
    commands:
    - git fetch --tags
    when:
      event: tag

  - name: test
    image: golang:latest
    commands:
      - go get github.com/golang/dep/cmd/dep
      - dep ensure -v
      - make test-prep
      - make test
    environment:
      GOPATH: /go
      GOBIN: /go/bin
      IMG: autonomy/cluster-api-provider-talos:latest
    depends_on:
    - fetch

  - name: build
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make docker-build
    volumes:
    - name: dockersock
      path: /var/run
    depends_on:
    - test

  - name: push
    image: autonomy/build-container:latest
    pull: always
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
    - make login
    - make docker-push
    volumes:
    - name: dockersock
      path: /var/run
    when:
      event:
        exclude:
        - pull_request
    depends_on:
    - build

volumes:
- name: dockersock
  temp: {}