// +build !ignore_autogenerated

/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosClusterControlPlaneSpec) DeepCopyInto(out *TalosClusterControlPlaneSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosClusterControlPlaneSpec.
func (in *TalosClusterControlPlaneSpec) DeepCopy() *TalosClusterControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(TalosClusterControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosClusterPlatformSpec) DeepCopyInto(out *TalosClusterPlatformSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosClusterPlatformSpec.
func (in *TalosClusterPlatformSpec) DeepCopy() *TalosClusterPlatformSpec {
	if in == nil {
		return nil
	}
	out := new(TalosClusterPlatformSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosClusterProviderSpec) DeepCopyInto(out *TalosClusterProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.ControlPlane = in.ControlPlane
	out.Platform = in.Platform
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosClusterProviderSpec.
func (in *TalosClusterProviderSpec) DeepCopy() *TalosClusterProviderSpec {
	if in == nil {
		return nil
	}
	out := new(TalosClusterProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TalosClusterProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosClusterProviderSpecList) DeepCopyInto(out *TalosClusterProviderSpecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TalosClusterProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosClusterProviderSpecList.
func (in *TalosClusterProviderSpecList) DeepCopy() *TalosClusterProviderSpecList {
	if in == nil {
		return nil
	}
	out := new(TalosClusterProviderSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TalosClusterProviderSpecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosClusterProviderSpecStatus) DeepCopyInto(out *TalosClusterProviderSpecStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosClusterProviderSpecStatus.
func (in *TalosClusterProviderSpecStatus) DeepCopy() *TalosClusterProviderSpecStatus {
	if in == nil {
		return nil
	}
	out := new(TalosClusterProviderSpecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosClusterProviderStatus) DeepCopyInto(out *TalosClusterProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosClusterProviderStatus.
func (in *TalosClusterProviderStatus) DeepCopy() *TalosClusterProviderStatus {
	if in == nil {
		return nil
	}
	out := new(TalosClusterProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TalosClusterProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosClusterProviderStatusList) DeepCopyInto(out *TalosClusterProviderStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TalosClusterProviderStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosClusterProviderStatusList.
func (in *TalosClusterProviderStatusList) DeepCopy() *TalosClusterProviderStatusList {
	if in == nil {
		return nil
	}
	out := new(TalosClusterProviderStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TalosClusterProviderStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosClusterProviderStatusSpec) DeepCopyInto(out *TalosClusterProviderStatusSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosClusterProviderStatusSpec.
func (in *TalosClusterProviderStatusSpec) DeepCopy() *TalosClusterProviderStatusSpec {
	if in == nil {
		return nil
	}
	out := new(TalosClusterProviderStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosClusterProviderStatusStatus) DeepCopyInto(out *TalosClusterProviderStatusStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosClusterProviderStatusStatus.
func (in *TalosClusterProviderStatusStatus) DeepCopy() *TalosClusterProviderStatusStatus {
	if in == nil {
		return nil
	}
	out := new(TalosClusterProviderStatusStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosMachinePlatformSpec) DeepCopyInto(out *TalosMachinePlatformSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosMachinePlatformSpec.
func (in *TalosMachinePlatformSpec) DeepCopy() *TalosMachinePlatformSpec {
	if in == nil {
		return nil
	}
	out := new(TalosMachinePlatformSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosMachineProviderSpec) DeepCopyInto(out *TalosMachineProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Platform = in.Platform
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosMachineProviderSpec.
func (in *TalosMachineProviderSpec) DeepCopy() *TalosMachineProviderSpec {
	if in == nil {
		return nil
	}
	out := new(TalosMachineProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TalosMachineProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosMachineProviderSpecList) DeepCopyInto(out *TalosMachineProviderSpecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TalosMachineProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosMachineProviderSpecList.
func (in *TalosMachineProviderSpecList) DeepCopy() *TalosMachineProviderSpecList {
	if in == nil {
		return nil
	}
	out := new(TalosMachineProviderSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TalosMachineProviderSpecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosMachineProviderSpecStatus) DeepCopyInto(out *TalosMachineProviderSpecStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosMachineProviderSpecStatus.
func (in *TalosMachineProviderSpecStatus) DeepCopy() *TalosMachineProviderSpecStatus {
	if in == nil {
		return nil
	}
	out := new(TalosMachineProviderSpecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosMachineProviderStatus) DeepCopyInto(out *TalosMachineProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosMachineProviderStatus.
func (in *TalosMachineProviderStatus) DeepCopy() *TalosMachineProviderStatus {
	if in == nil {
		return nil
	}
	out := new(TalosMachineProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TalosMachineProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosMachineProviderStatusList) DeepCopyInto(out *TalosMachineProviderStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TalosMachineProviderStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosMachineProviderStatusList.
func (in *TalosMachineProviderStatusList) DeepCopy() *TalosMachineProviderStatusList {
	if in == nil {
		return nil
	}
	out := new(TalosMachineProviderStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TalosMachineProviderStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosMachineProviderStatusSpec) DeepCopyInto(out *TalosMachineProviderStatusSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosMachineProviderStatusSpec.
func (in *TalosMachineProviderStatusSpec) DeepCopy() *TalosMachineProviderStatusSpec {
	if in == nil {
		return nil
	}
	out := new(TalosMachineProviderStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosMachineProviderStatusStatus) DeepCopyInto(out *TalosMachineProviderStatusStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosMachineProviderStatusStatus.
func (in *TalosMachineProviderStatusStatus) DeepCopy() *TalosMachineProviderStatusStatus {
	if in == nil {
		return nil
	}
	out := new(TalosMachineProviderStatusStatus)
	in.DeepCopyInto(out)
	return out
}
